<!DOCTYPE html> 
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <link type="text/css" href="/marvelous_resource/css/jquery.mobile.simpledialog.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/marvelous_resource/themes/jquery-mobile-marvelous.min.css">
    <link type="text/css" href="/marvelous_resource/css/style.css" rel="stylesheet"/>
    <script src="//code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="//code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <script src="/marvelous_resource/js/jquery.mobile.simpledialog2.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <style>
        .ui-title {
            margin: 0.6em 0% .8em !important;
        }
    </style>
</head>

<body style="height:100%">
    <div data-role="page">
        <div data-role="header">
            <h1 style ="width: 100%; margin-left:0"><img src="/marvelous_resource/img/marvelous.png" style="height: 24px; width: 24px; vertical-align: bottom;"> Marvelous Connect</h1>
        </div>
        <div data-role="content"> 
            <center>
                <div><?php printf($this->translate->_("Your ID federation between %1\$s and Marvelous Connect is the following conditions."), $this->translate->_($this->applicationName)); ?></div>
            </center>
            <br>
            <div id="table-container">
                <table>
                    <tbody>
                        <?php
                        foreach ($this->platforms as $platform) {

                            $name       = $platform->getPlatformName();
                            $platformId = $platform->getPlatformId();

                            if (!file_exists(implode(array(APPLICATION_PATH, '..', 'public', 'marvelous_resource', 'img', 'login', $this->translate->getLocale(), $name), DIRECTORY_SEPARATOR))) {
                                continue;
                            }

                            $checked                          = in_array($platform->getPlatformId(), $this->platformIds) ? 'checked' : '';
                            $this->queryParams['platform_id'] = $platformId;
                            $createIdFederation               = '/marvelous/federation?' . http_build_query($this->queryParams);
                            $cancelIdFederation               = '/marvelous/federation/cancel-application-user-federation?' . http_build_query($this->queryParams);
                            $login                            = ($platformId == $this->loginPlatformId) ? 'true' : 'false';

                            echo '<tr>
                            <td><img src="/marvelous_resource/img/index/' . $name . '" style="width:24px; height:24px; vertical-align: middle; margin-right: 4px;">' . $name . '</td>
                            <td>
                                <div class="onoffswitch">
                                    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="' . strtolower($name) . '-onoffswitch" data-name="' . $name . '" data-role="none" data-createidfederation="' . $createIdFederation . '" data-cancelidfederation="' . $cancelIdFederation . '" data-login="' . $login . '" ' . $checked . '>
                                    <label class="onoffswitch-label" for="' . strtolower($name) . '-onoffswitch">
                                        <div class="onoffswitch-inner"></div>
                                        <div class="onoffswitch-switch"></div>
                                    </label>
                                </div>
                            </td>
                        </tr>';
                        }
                        ?>

                    </tbody>
                </table>
            </div>
            <br>
            <div>
                <a href="<?php echo $this->redirectUri ?>" data-role="button"  data-shadow="false"><?php print($this->translate->_("Back")); ?></a>
            </div>
            <div>
                <a href="<?php print($this->translate->_("http://www.marv.jp/privacy_policy/")) ?>" data-role="button" data-shadow="false"><?php print($this->translate->_("Privacy Policy")) ?></a>
            </div>
        </div>
        <script>
            $(document).ready(function() {

                $('#table-container').css('max-height', ~~(screen.height * 0.6) + 'px');

                $('#moog-signup').on('mousedown touchstart', function() {
                    $(this).addClass('hover');
                });
                $('#moog-signup').on('mouseup toudchend mousemove touchmove', function(e) {
                    $(this).removeClass('hover');
                    return false;
                });
                $('#moog-signup').parent().on('mousemove touchmove', function() {
                    $('#moog-signup').removeClass('hover');
                });

                $('input.onoffswitch-checkbox').on('change', function(e) {
                    var target = $(e.target);
                    if (target.prop('checked')) {
                        $('<div>').simpledialog2({
                            mode: 'button',
                            headerText: '<?php print($this->translate->_("ID federation confirmation")); ?>',
                            headerClose: false,
                            buttonPrompt: '<?php print($this->translate->_("ID federation with ")); ?>' + target.attr('data-name') + '<?php print($this->translate->_(" will be done")); ?>' + '<?php print($this->translate->_("<br>(After the ID federation, the app will be relaunched).")); ?>',
                            buttons: {
                                'OK': {
                                    click: function() {
                                        target.prop('checked', true);
                                        window.location.href = target.attr('data-createidfederation');
                                    },
                                    shadow: false
                                },
                                '<?php print($this->translate->_("Cancel")); ?>': {
                                    click: function() {
                                        target.prop('checked', false);
                                    },
                                    shadow: false
                                }
                            }
                        });
                    } else {
                        var messeage = '<?php print($this->translate->_("period")) ?>';
                        if (target.attr('data-login') === 'true')
                        {
                            messeage = "<?php print($this->translate->_("<br>(After the cancellation, login page will be reloaded).")); ?>";
                        }

                        $('<div>').simpledialog2({
                            mode: 'button',
                            headerText: '<?php print($this->translate->_("ID federation confirmation")); ?>',
                            headerClose: false,
                            buttonPrompt: '<?php print($this->translate->_("ID federation with ")); ?>' + target.attr('data-name') + '<?php print($this->translate->_(" will be canceled")); ?>' + messeage,
                            buttons: {
                                'OK': {
                                    click: function() {
                                        target.prop('checked', false);
                                        window.location.href = target.attr('data-cancelidfederation');
                                    },
                                    shadow: false
                                },
                                '<?php print($this->translate->_("Cancel")); ?>': {
                                    click: function() {
                                        target.prop('checked', true);
                                    },
                                    shadow: false
                                }
                            }
                        });
                    }
                });


            });


        </script>
    </div>
</body>