<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
</head>
<h3>
   掲示板ログイン
</h3>
<form class="pure-form" method="post">
    <div id="error"></div>
    <input id="u" type="text" name="u" placeholder="ユーザ名">
    <button type="submit" onClick="return onClick()" class="pure-button pure-button-primary">ログイン</button>
</form>
<script>
    function onClick() {
        if (!document.querySelector('#u').value.length) {
            document.querySelector('#error').innerHTML  = 'ユーザ名を入力して下さい';
            return false;
        }
        document.querySelector('#error').innerHTML  = '';
    }
</script>